"""Issue transform runner.

This module:
- Copies optional asset directories into the build output (keeping figs/ and images/ separate)
- Runs the configured issue-level XSLT stylesheet against each XML file in xml/
- Writes toc.html as generated by XSLT (preferred) OR generates a minimal toc if XSLT doesn't create one.

We intentionally keep this runner generic; your XSLT controls the final HTML design.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Dict, Optional, List

from lxml import etree

DEFAULT_NS = [
    "http://specifications.silverchair.com/xsd/1/22/SCJATS-journalpublishing.xsd",
    "http://specifications.silverchair.com/xsd/1/27/SCJATS-journalpublishing.xsd",
    "http://specifications.silverchair.com/xsd/1/47/SCJATS-journalpublishing.xsd",
    ]

# Example namespaces you may want to strip from attributes
JATS_NS   = "http://jats.nlm.nih.gov"          # your default set already covers element tags
XLINK_NS  = "http://www.w3.org/1999/xlink" 
MML_NS    = "http://www.w3.org/1998/Math/MathML"
XML_NS    = "http://www.w3.org/XML/1998/namespace"  # usually keep (xml:lang, etc.)
XSI_NS    = "http://www.w3.org/2001/XMLSchema-instance"


OPTIONAL_DIRS = ["eqs", "figs", "images", "media", "pdfs", "xml"]


def strip_default_namespace_everywhere(
        doc,
        strip_attr_namespaces=(XLINK_NS, MML_NS, XSI_NS),   # which attribute namespaces to drop → localname
        keep_attr_namespaces=(XML_NS,)              # namespaces to preserve on attributes
    ):
    root = doc.getroot()

    # 1) Elements: move from the default JATS namespace into no-namespace
    for el in root.iter():
        if not isinstance(el.tag, str):  # skip comments/PIs/etc.
            continue
        q = etree.QName(el)
        if q.namespace in DEFAULT_NS:
            el.tag = q.localname  # element now has no namespace

        # 2) Attributes: rebuild el.attrib, stripping chosen namespaces
        if el.attrib:
            new_attrib = {}
            for k, v in el.attrib.items():
                if not isinstance(k, str):
                    # very rare, defensive
                    new_attrib[k] = v
                    continue

                qk = etree.QName(k)
                ns = qk.namespace

                if ns is None:
                    # already unprefixed, keep as-is
                    new_attrib[k] = v
                elif ns in keep_attr_namespaces:
                    # keep xml:* etc.
                    new_attrib[k] = v
                elif ns in strip_attr_namespaces:
                    # drop the namespace → use the localname only
                    local = qk.localname
                    # If there’s a collision, last one wins; customize if needed
                    new_attrib[local] = v
                else:
                    # attribute from an unknown/preserved ns → keep fully qualified
                    new_attrib[k] = v

            # overwrite attributes in place
            el.attrib.clear()
            el.attrib.update(new_attrib)

    # 3) Remove unused xmlns declarations, preserve ones still referenced
    etree.cleanup_namespaces(root)
    return doc


def copy_optional_dirs(src_root: Path, dst_root: Path) -> None:
    for name in OPTIONAL_DIRS:
        s = src_root / name
        if s.exists() and s.is_dir():
            d = dst_root / name
            if d.exists():
                shutil.rmtree(d, ignore_errors=True)
            shutil.copytree(s, d)


def run_xslt_on_issue(xml_dir: Path, output_root: Path, stylesheet_path: Path) -> List[Path]:
    """Apply XSLT to each XML file and write HTML outputs.

    Returns list of generated article HTML paths.
    """
    xslt_doc = etree.parse(str(stylesheet_path))
    transform = etree.XSLT(xslt_doc)

    out_html_dir = output_root  # articles at root unless your XSLT chooses otherwise
    out_html_dir.mkdir(parents=True, exist_ok=True)

    generated: List[Path] = []
    for xml_file in sorted(xml_dir.glob("*.xml")):
        doc = etree.parse(str(xml_file))
        # remove the default namespace if present
        doc = strip_default_namespace_everywhere(doc)
        params = {
            "xml-basename": etree.XSLT.strparam(xml_file.stem),
        }
        
        
        result = transform(doc, **params)
        html_name = xml_file.stem + ".html"
        html_path = out_html_dir / html_name
        html_path.write_bytes(etree.tostring(result, pretty_print=True, method="html", encoding="utf-8"))
        generated.append(html_path)

    return generated


def ensure_toc(output_root: Path, generated_html: List[Path]) -> Path:
    """Ensure a toc.html exists.

    If XSLT did not create one, generate a minimal TOC linking to article HTML files.
    """
    toc = output_root / "toc.html"
    if toc.exists():
        return toc

    # Minimal fallback TOC: simple list
    items = "\n".join([f'<li><a href="{p.name}">{p.stem}</a></li>' for p in generated_html])
    toc.write_text(
        "<!doctype html><html><head><meta charset='utf-8'><title>Table of Contents</title></head>"
        "<body><h1>Table of Contents</h1><ul>" + items + "</ul></body></html>",
        encoding="utf-8"
    )
    return toc
