"""Issue transform runner.

This module:
- Copies optional asset directories into the build output (keeping figs/ and images/ separate)
- Runs the configured issue-level XSLT stylesheet against each XML file in xml/
- Writes toc.html as generated by XSLT (preferred) OR generates a minimal toc if XSLT doesn't create one.

We intentionally keep this runner generic; your XSLT controls the final HTML design.
"""

from __future__ import annotations

import shutil, os
from pathlib import Path
from typing import Dict, Optional, List
from PIL import Image
from lxml import etree

DEFAULT_NS = [
    "http://specifications.silverchair.com/xsd/1/22/SCJATS-journalpublishing.xsd",
    "http://specifications.silverchair.com/xsd/1/27/SCJATS-journalpublishing.xsd",
    "http://specifications.silverchair.com/xsd/1/47/SCJATS-journalpublishing.xsd",
    ]

# Example namespaces you may want to strip from attributes
JATS_NS   = "http://jats.nlm.nih.gov"          # your default set already covers element tags
XLINK_NS  = "http://www.w3.org/1999/xlink" 
MML_NS    = "http://www.w3.org/1998/Math/MathML"
XML_NS    = "http://www.w3.org/XML/1998/namespace"  # usually keep (xml:lang, etc.)
XSI_NS    = "http://www.w3.org/2001/XMLSchema-instance"


OPTIONAL_DIRS = ["eqs", "figs", "images", "media", "pdfs", "xml",]
# JPEG_CONF = ["eqs", "figs", "images",]
BUILD_JPEGS_CONF = [  # source, destination, size
                    ["eqs","thumbs",200],
                    ["figs","thumbs",200],
                    ["images","thumbs",200],
                    ["images","figs",0],
                    ["eqs","eqs",0],
                  ]
THUMB_WIDTH = 200

def generate_jpegs(source_dir, destination_dir, max_width = 0, ignore_jpeg = False):
    # Loop through all files in directory
    print("Generate jpegs", flush=True)
    for filename in source_dir.iterdir():
        print(filename, flush=True)
        if not filename.is_file():
            continue
        if ignore_jpeg and filename.suffix.lower() in ['jpeg','jpg','jpe']:
            continue
        file_path = source_dir / filename
        try:
            # Open the image
            with Image.open(file_path) as img:
                if max_width > 0:
                    # Calculate new dimensions maintaining aspect ratio
                    width, height = img.size
                    if width > max_width:
                        ratio = max_width / float(width)
                        new_height = int(height * ratio)
                        img = img.resize((max_width, new_height), Image.LANCZOS)
    
                # Convert to RGB (JPEG doesn’t support transparency)
                img = img.convert("RGB")
    
                # Output file path (same name, .jpg extension)
                base_name = filename.stem
                out_path = destination_dir / f"{base_name}.jpg"
                print(out_path)
                # Save as JPEG (quality=85 is a good balance)
                img.save(out_path, "JPEG", quality=90)
    
        except Exception as e:
            print(f"Skipping {filename}: {e}")


def strip_default_namespace_everywhere(
        doc,
        strip_attr_namespaces=(XLINK_NS, MML_NS, XSI_NS),   # which attribute namespaces to drop → localname
        keep_attr_namespaces=(XML_NS,)              # namespaces to preserve on attributes
    ):
    root = doc.getroot()

    # 1) Elements: move from the default JATS namespace into no-namespace
    for el in root.iter():
        if not isinstance(el.tag, str):  # skip comments/PIs/etc.
            continue
        q = etree.QName(el)
        if q.namespace in DEFAULT_NS:
            el.tag = q.localname  # element now has no namespace

        # 2) Attributes: rebuild el.attrib, stripping chosen namespaces
        if el.attrib:
            new_attrib = {}
            for k, v in el.attrib.items():
                if not isinstance(k, str):
                    # very rare, defensive
                    new_attrib[k] = v
                    continue

                qk = etree.QName(k)
                ns = qk.namespace

                if ns is None:
                    # already unprefixed, keep as-is
                    new_attrib[k] = v
                elif ns in keep_attr_namespaces:
                    # keep xml:* etc.
                    new_attrib[k] = v
                elif ns in strip_attr_namespaces:
                    # drop the namespace → use the localname only
                    local = qk.localname
                    # If there’s a collision, last one wins; customize if needed
                    new_attrib[local] = v
                else:
                    # attribute from an unknown/preserved ns → keep fully qualified
                    new_attrib[k] = v

            # overwrite attributes in place
            el.attrib.clear()
            el.attrib.update(new_attrib)

    # 3) Remove unused xmlns declarations, preserve ones still referenced
    etree.cleanup_namespaces(root)
    return doc


def copy_optional_dirs(ctx, src_root: Path, dst_root: Path) -> None:
    for name in OPTIONAL_DIRS:
        s = src_root / name
        if s.exists() and s.is_dir():
            d = dst_root / name
            if d.exists():
                shutil.rmtree(d, ignore_errors=True)
            shutil.copytree(s, d)


# def build_thumbs_dir(ctx, src_root: Path, dst_root: Path) -> None:
#     print("build_thumbs_dir", flush=True)
#     # we build thumbs from source image directories such as 'figs' and 'eqs'
#     d = dst_root / 'thumbs'
#     print(d, flush=True)
#     if d.exists():
#         shutil.rmtree(d, ignore_errors=True)
#     for name in THUMB_SRC_DIRS:
#         d.mkdir(parents=True, exist_ok=True)
#         s = src_root / name
#         if s.is_dir():
#             print(s, flush=True)
#             generate_jpegs(s, d, max_width=THUMB_WIDTH)
# 
# 
# def build_full_jpegs(ctx, src_root: Path, dst_root: Path) -> None:
#     print("build_figs_jpegs", flush=True)
#     # we build full sized jpegs from source image directories 
#     for source, destination in FULL_JPEG_DIRS:
#     s = src_root / source
#     d = dst_root / destination
#     if s.exists() and s.is_dir():
#         d.mkdir(parents=True, exist_ok=True)
#         s = src_root / name
#         if s.is_dir():
#             print(s, flush=True)
#             generate_jpegs(s, d, max_width=THUMB_WIDTH)

def build_jpegs(ctx, src_root: Path, dst_root: Path) -> None:
    print("build_jpegs", flush=True)
    # we build jpegs from source image directories such as 'figs' and 'eqs'
    for source, destination, size in BUILD_JPEGS_CONF:
        s = src_root / source
        if not s.is_dir():
            continue
        d = dst_root / destination
        d.mkdir(parents=True, exist_ok=True)
        generate_jpegs(s, d, max_width=size)


def run_xslt_on_issue(xml_dir: Path, output_root: Path, stylesheet_path: Path) -> List[Path]:
    """Apply XSLT to each XML file and write HTML outputs.

    Returns list of generated article HTML paths.
    """
    xslt_doc = etree.parse(str(stylesheet_path))
    transform = etree.XSLT(xslt_doc)

    out_html_dir = output_root / "html"  # articles at root unless your XSLT chooses otherwise
    out_html_dir.mkdir(parents=True, exist_ok=True)

    out_figs_dir = output_root / "figs"  # articles at root unless your XSLT chooses otherwise
    out_figs_dir.mkdir(parents=True, exist_ok=True)

    generated: List[Path] = []
    for xml_file in sorted(xml_dir.glob("*.xml")):
        doc = etree.parse(str(xml_file))
        # remove the default namespace if present
        doc = strip_default_namespace_everywhere(doc)
        params = {
            "xml-basename": etree.XSLT.strparam(xml_file.stem),
        }
        
        result = transform(doc, **params)
        html_name = xml_file.stem + ".html"
        html_path = out_html_dir / html_name
        html_path.write_bytes(etree.tostring(result, pretty_print=True, method="html", encoding="utf-8"))
        generated.append(html_path)
        print(html_path)
        
        ## Build out corresponding figure pages            
        figure_ids = doc.xpath("//fig/@id")        
        for figure_id in figure_ids:
            print(figure_id)
            if not os.path.exists(out_figs_dir):
                os.makedirs(out_figs_dir)
            #############################################
            # Build a figure page
            params = {
                "xml-basename": etree.XSLT.strparam(xml_file.stem),
                "figure-id": etree.XSLT.strparam(figure_id),
            }
            result = transform(doc, **params)
            # Write output
            html_name = xml_file.stem + "." + figure_id + ".html"
            html_path = out_figs_dir / html_name
            html_path.write_bytes(etree.tostring(result, pretty_print=True, method="html", encoding="utf-8"))


    return generated


def ensure_toc(output_root: Path, generated_html: List[Path]) -> Path:
    """Ensure a toc.html exists.

    If XSLT did not create one, generate a minimal TOC linking to article HTML files.
    """
    toc = output_root / "toc.html"
    if toc.exists():
        return toc

    # Minimal fallback TOC: simple list
    items = "\n".join([f'<li><a href="{p.name}">{p.stem}</a></li>' for p in generated_html])
    toc.write_text(
        "<!doctype html><html><head><meta charset='utf-8'><title>Table of Contents</title></head>"
        "<body><h1>Table of Contents</h1><ul>" + items + "</ul></body></html>",
        encoding="utf-8"
    )
    return toc
